name: Nick Sheffield
description: Some kind of web developer
meta_description: "Some kind of web developer"
author_bio: "I'm a front-end developer from Auckland, NZ"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://nsheff.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
permalink: /:title
timezone: Pacific/Auckland

# Details for the RSS feed generator
url:            'http://nsheff.com'
author:         'Nick Sheffield'


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      post_class: post-template
      layout: post